@echo off
echo Initializing Git...
git init
echo Adding all files...
git add .
echo Committing changes...
git commit -m "Project Update: Full UI Overhaul and Interactive Features"
echo Setting branch to main...
git branch -M main
echo Adding remote repository...
git remote add origin https://github.com/BHADDRESH1/swetcha.git
echo Pushing to GitHub...
git push -u origin main
echo.
echo Process Complete! If there were errors above, please check if Git is installed.
pause
